[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Igor Veksler <igor.veksler@wandb.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
